In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Let's make some fake data which contains x,y,z coordinates of points in a box

In [10]:
coord1 = np.array([1,2,-5])
coord2 = np.array([2,-2,10])

l  = ((coord2[0] - coord1[0])**2 + (coord2[1] - coord1[1])**2 + (coord2[2] - coord1[2])**2)**.5
print l

15.556349186104045


In [15]:
(np.sum((coord2-coord1)**2))**0.5

15.556349186104045

In [16]:
# this is 2 by 3 array containing the coordinates of two galaxies 
coord_rest  =  np.array([[2,-2,10],[1,4,5]])
print coord_rest

[[ 2 -2 10]
 [ 1  4  5]]


In [19]:
for i in range(2): 
    
    print "coordinate of the galaxy" , coord_rest[i]
    
    print "distance between the galaxy and galaxy 1" , (np.sum((coord_rest[i] - coord1)**2))**0.5

coordinate of the galaxy [ 2 -2 10]
distance between the galaxy and galaxy 1 15.556349186104045
coordinate of the galaxy [1 4 5]
distance between the galaxy and galaxy 1 10.198039027185569


In [24]:
print coord_rest
print coord1

[[ 2 -2 10]
 [ 1  4  5]]
[ 1  2 -5]


In [26]:
coord_rest - coord1[None,:]

array([[ 1, -4, 15],
       [ 0,  2, 10]])

In [28]:
for i in range(2): 
    
    #print "coordinate of the galaxy" , coord_rest[i]
    
    print coord_rest[i] - coord1

[ 1 -4 15]
[ 0  2 10]


In [29]:
(coord_rest - coord1[None,:])**2

array([[  1,  16, 225],
       [  0,   4, 100]])

In [31]:
(np.sum( (coord_rest - coord1[None,:])**2 , axis = 1))**0.5

array([15.55634919, 10.19803903])

# A few examples about a cool trick in broadcasting (arr1 , arr2)

In [37]:
arr1 = np.array([[1,2,2],[3,2,45]])
print arr1.shape
print arr1

(2, 3)
[[ 1  2  2]
 [ 3  2 45]]


In [38]:
arr2 = np.array([1,2])
print arr2.shape
print arr2

(2,)
[1 2]


In [40]:
arr3 = np.array([1,2,3])
print arr3.shape
arr3

(3,)


array([1, 2, 3])

In [39]:
arr1 * arr2[:,None]

array([[ 1,  2,  2],
       [ 6,  4, 90]])

In [41]:
arr1 * arr3[None,:]

array([[  1,   4,   6],
       [  3,   4, 135]])

# A few example about  np.sum

In [43]:
arr1

array([[ 1,  2,  2],
       [ 3,  2, 45]])

In [44]:
np.sum(arr1)

55

In [45]:
np.sum(arr1, axis = 0)

array([ 4,  4, 47])

In [47]:
np.sum(arr1, axis = 1)

array([ 5, 50])

Now let's look at a higher dimensional array

In [51]:
Q = np.random.rand(2,3,3)
print Q

[[[0.43576836 0.9221568  0.79752544]
  [0.06213021 0.81079375 0.03846438]
  [0.71399978 0.81333921 0.92719043]]

 [[0.86903332 0.52574248 0.86767545]
  [0.05663544 0.07513026 0.2253142 ]
  [0.51126149 0.39418497 0.83106911]]]


In [53]:
print np.sum(Q, axis = 0)

[[1.30480168 1.44789928 1.66520089]
 [0.11876564 0.88592401 0.26377857]
 [1.22526127 1.20752418 1.75825955]]


In [54]:
print np.sum(Q, axis = 1)

[[1.21189835 2.54628977 1.76318025]
 [1.43693024 0.9950577  1.92405876]]


In [55]:
print np.sum(Q, axis = 2)

[[2.15545061 0.91138833 2.45452943]
 [2.26245125 0.35707989 1.73651557]]


# A few examples regarding arr[i:j]

In [60]:
A = np.arange(10)
#print A
B = np.array([0,4,2,5,6,7,1,2,6,9])
print B

[0 4 2 5 6 7 1 2 6 9]


In [62]:
B[5:9]

array([7, 1, 2, 6])

In [67]:
print B[-1] 
print B[-2]

9
6


In [66]:
B[-2:-1]

array([6])

# A few examples regarding masking numpy arrays

In [68]:
A = 10 * np.random.rand(34)

In [69]:
A

array([8.54099034, 1.28701061, 8.51039101, 5.77622464, 6.10376005,
       4.85747476, 5.38991348, 7.63320314, 4.48508993, 7.31128563,
       6.47594407, 5.01083287, 1.62095808, 8.81156447, 9.70452054,
       5.14771637, 7.16924883, 4.46491153, 6.38332588, 9.65197158,
       7.85752058, 3.12788622, 8.40361061, 6.44472136, 7.69319428,
       3.19737059, 1.23403046, 0.71110031, 1.55560767, 4.81227547,
       6.03860167, 4.22471873, 4.96698703, 7.59810285])

Now let's keep elements of A that are above 4

In [70]:
mask = A>4

In [72]:
mask

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True,  True])

In [73]:
A[mask]

array([8.54099034, 8.51039101, 5.77622464, 6.10376005, 4.85747476,
       5.38991348, 7.63320314, 4.48508993, 7.31128563, 6.47594407,
       5.01083287, 8.81156447, 9.70452054, 5.14771637, 7.16924883,
       4.46491153, 6.38332588, 9.65197158, 7.85752058, 8.40361061,
       6.44472136, 7.69319428, 4.81227547, 6.03860167, 4.22471873,
       4.96698703, 7.59810285])

In [76]:
A[A>4]

array([8.54099034, 8.51039101, 5.77622464, 6.10376005, 4.85747476,
       5.38991348, 7.63320314, 4.48508993, 7.31128563, 6.47594407,
       5.01083287, 8.81156447, 9.70452054, 5.14771637, 7.16924883,
       4.46491153, 6.38332588, 9.65197158, 7.85752058, 8.40361061,
       6.44472136, 7.69319428, 4.81227547, 6.03860167, 4.22471873,
       4.96698703, 7.59810285])

In [74]:
~mask

array([False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True,  True,
        True,  True, False, False, False, False, False])

In [75]:
A[~mask]

array([1.28701061, 1.62095808, 3.12788622, 3.19737059, 1.23403046,
       0.71110031, 1.55560767])

In [77]:
A[~(A>4)]

array([1.28701061, 1.62095808, 3.12788622, 3.19737059, 1.23403046,
       0.71110031, 1.55560767])

Now let's look at some higher dimensional arrays

In [78]:
B = 10*np.random.rand(34,3)

In [79]:
B

array([[7.74985678, 2.76730996, 0.88505262],
       [7.28078444, 4.74629588, 0.59962287],
       [0.05110999, 2.6285805 , 5.83533034],
       [2.45333416, 2.8711551 , 7.59156432],
       [7.31109141, 6.05096371, 5.60647528],
       [9.47178103, 1.80302064, 1.35031191],
       [1.42011148, 0.15355724, 2.5970873 ],
       [9.57133226, 3.76169572, 1.89573186],
       [5.57442712, 0.10182407, 3.61641004],
       [7.39256212, 0.72234504, 7.92771347],
       [9.88117024, 2.03222082, 5.19555611],
       [6.33089372, 0.61477092, 2.32422357],
       [0.03134309, 5.1906842 , 5.06564521],
       [3.0877809 , 5.56286544, 6.92259139],
       [3.05750208, 2.81064175, 5.03878658],
       [3.2909273 , 7.10983101, 0.12815808],
       [2.9704945 , 4.60161882, 3.76151655],
       [3.7097513 , 3.52116952, 9.26107001],
       [9.82089497, 9.48488236, 4.70141692],
       [9.86987162, 9.24748594, 6.44275392],
       [7.46364793, 7.01362575, 8.40300868],
       [7.84663219, 7.90419478, 0.17976922],
       [9.

In [85]:
mask_rows = A>4
mask_rows

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True,  True])

In [86]:
B[mask_rows,:]

array([[7.74985678, 2.76730996, 0.88505262],
       [0.05110999, 2.6285805 , 5.83533034],
       [2.45333416, 2.8711551 , 7.59156432],
       [7.31109141, 6.05096371, 5.60647528],
       [9.47178103, 1.80302064, 1.35031191],
       [1.42011148, 0.15355724, 2.5970873 ],
       [9.57133226, 3.76169572, 1.89573186],
       [5.57442712, 0.10182407, 3.61641004],
       [7.39256212, 0.72234504, 7.92771347],
       [9.88117024, 2.03222082, 5.19555611],
       [6.33089372, 0.61477092, 2.32422357],
       [3.0877809 , 5.56286544, 6.92259139],
       [3.05750208, 2.81064175, 5.03878658],
       [3.2909273 , 7.10983101, 0.12815808],
       [2.9704945 , 4.60161882, 3.76151655],
       [3.7097513 , 3.52116952, 9.26107001],
       [9.82089497, 9.48488236, 4.70141692],
       [9.86987162, 9.24748594, 6.44275392],
       [7.46364793, 7.01362575, 8.40300868],
       [9.98903034, 6.15022447, 6.51568696],
       [1.26178909, 4.51987705, 1.9991888 ],
       [8.58454403, 2.17834784, 3.83282456],
       [5.

In [88]:
C = 10*np.random.rand(3)
print C

[0.98584383 1.46027181 6.66977679]


In [89]:
mask_column = C>4
print mask_column

[False False  True]


In [90]:
B[:,mask_column]

array([[0.88505262],
       [0.59962287],
       [5.83533034],
       [7.59156432],
       [5.60647528],
       [1.35031191],
       [2.5970873 ],
       [1.89573186],
       [3.61641004],
       [7.92771347],
       [5.19555611],
       [2.32422357],
       [5.06564521],
       [6.92259139],
       [5.03878658],
       [0.12815808],
       [3.76151655],
       [9.26107001],
       [4.70141692],
       [6.44275392],
       [8.40300868],
       [0.17976922],
       [6.51568696],
       [1.9991888 ],
       [3.83282456],
       [5.29603641],
       [7.30619364],
       [3.56084871],
       [5.75626727],
       [2.3279278 ],
       [3.11963177],
       [4.53308896],
       [6.654262  ],
       [3.85534349]])

# MEDIAN and AVERAGE (MEAN)

In [1]:
import numpy as np

In [3]:
arr = 10*np.random.rand(12)

In [4]:
arr

array([7.41610554, 1.15562404, 1.6329942 , 5.60696042, 7.05131667,
       0.3022866 , 3.65894374, 9.89097211, 3.44817849, 2.84168707,
       0.54663045, 3.86409151])

In [5]:
np.mean(arr)

3.9513159027490374

In [8]:
np.median(arr)

3.553561116091858

In [9]:
arr = np.array([1,2,5,8,10,4,11])

print arr[arr<5]
print arr[arr>5]

[1 2 4]
[ 8 10 11]


In [10]:
np.median(arr)

5.0

In [11]:
np.sort(arr)

array([ 1,  2,  4,  5,  8, 10, 11])